#!/bin/bash

RESOURCES='./resources'

case "$1" in
	1)	notify-send --icon=wakatime 'Waka Time Notification' 'Daemon started'
		aplay -q $RESOURCES/start.wav
		;;
	2) 	notify-send --icon=wakatime 'Congrats!!' 'Your leaderboard rank is '$2 
		aplay -q $RESOURCES/congrats.wav
		;;
	*)  echo "Invalid Option"
esac